name = "MultiResidue"
uuid = "15ac1977-6a35-4422-b111-63c1dba6b911"
authors = ["gangchen "]
version = "1.5.0"

[deps]
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"

[compat]
InvertedIndices = "1.1"
LinearAlgebra = "1.7"
SymEngine = "0.8.7"
julia = "1.0, 1.7"
